on: push
name: build
jobs:
  build:
    name: build and push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master 
    - name: Preparation
      run: |
        REGISTRY="docker.pkg.github.com"
        IMAGE="${REGISTRY}/${{ github.repository }}/pythonslimrun"
        TAGS="${IMAGE}:$GITHUB_REF"
        if [[ $GITHUB_REF == ref/head/master ]]; then
          TAGS="${TAGS},${IMAGE}:latest"
        fi
        echo ::set-output name=tags::${TAGS}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: docker.pkg.github.com
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }} 
    - name: build and push to docker
      uses: docker/build-push-action@v2
      with:
        file: ./Dockerfile
        push: true
        tags: ${{ steps.prep.outputs.tags }}
