on: push
name: build
jobs:
  build:
    name: build and push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master 
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: docker.pkg.github.com
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }} 
    - name: build and push to docker
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/386,linux/amd64
        push: true
        tags: docker.pkg.github.com/darfig/pythonslimrun/pythonslimrun:latest
