on: push
name: build
jobs:
  build:
    name: build and push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master 
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: docker.pkg.github.com
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }} 
    - name: build and push to docker
      uses: docker/build-push-action@v2
      with:
        tags: docker.pkg.github.com/darfig/pythonslimrun/pythonslimrun:latest
