on: push
name: build
jobs:
  build:
    name: build and push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master 
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }} 
    - name: build and push to docker
      uses: docker/build-push-action@v2
      with:
        repository: ${{ github.repository }}
        tags: ghcr.io/user/app:latest
